server:
  port: 8080

spring:
  application:
    name: TaskBoard.Service.Boot

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:8081/realms/TodoRealm}
          jwk-set-uri: ${KEYCLOAK_REALM_URI:http://localhost:8081/realms/TodoRealm}/protocol/openid-connect/certs

keycloak:
  auth-server-url: ${KEYCLOAK_REALM_URI:http://localhost:8081/realms/TodoRealm}/protocol/openid-connect/token
  logout-server-url: ${KEYCLOAK_REALM_URI:http://localhost:8081/realms/TodoRealm}/protocol/openid-connect/logout
  client-id: my-client
