# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish Maven Package

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Restore dependencies
        run: mvn -B dependency:resolve

      - name: Build and run tests
        run: mvn -B clean verify

      - name: Publish to GitHub Packages
        run: mvn deploy -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
